[server]
host = ""
port = 8989
basePath = ""

[log]
logFilePath = "speedtest.log"
maxLogSize = 5 # MB

[ipinfo]
model = "ip" # ip(self-hosted) or ipinfo(ipinfo.io) todo
ipinfo_api_key = ""

[database]
model = "bolt" 
path = "speedtest.db"

[frontend]
chartlist = 100 # 默认显示最近100条数据


